## Parameter file editor

Function to calculate the Gamma scale parameter for parameter files generated through HSO, and add this to the parameter file. Input is file path to parameter file, and name of catchment. 

$G_{sh}=1$

$G_{sc}=\frac{\Delta t}{MRT}$

In [1]:
import pandas as pd

In [2]:
# catchment = "Gaupne"
# catchment = "Austdalsvatnet"
# catchment = "Tunsbergdalsvatnet"
# catchment= "Myklemyr"
# catchment = "BåtedølaS"
# catchment = "Geisdalsvatnet"
# catchment = "Fonndøla"
catchment = "Nigard"

In [3]:
def parameter_editor(file_path, catchment):
    df = pd.read_csv(file_path, sep=";", header=None)

    print(f"{catchment}:")
    print(f"MRT = {df.iloc[31,1]} days.")
    print(f"Timeresinsec = {df.iloc[26,1]} seconds.")

    GshInt = 1
    GscInt = float(df.iloc[26,1]) / (float(df.iloc[31,1]) * 3600 * 24)
    print("GscInt =", GscInt)

    df.loc[31, 0] = "GshInt"
    df.loc[31, 1] = GshInt

    new_row = pd.DataFrame([["GscInt", GscInt]])
    df = pd.concat([df.iloc[:32], new_row, df.iloc[32:]]).reset_index(drop=True)
    
    new_file_path = file_path.replace(".csv", "_edited.csv")
    df.to_csv(new_file_path, sep=";", header=False, index=False)

    print(f"File saved as: {new_file_path}")
    return df

file_path = f"{catchment}_1H_param.csv"
# file_path = f"{catchment}_3H_param.csv"
parameter_editor(file_path, catchment)

Nigard:
MRT = 11.262139671380568 days.
Timeresinsec = 3600.0 seconds.
GscInt = 0.0036997114120818713
File saved as: Nigard_1H_param_edited.csv

                                       0       1
0                               OBJECTID  3669.0
1                                     ID     1.0
2   b843f6d4-51ef-4309-8632-d7c4c90fdeca    10.0
3                                 076.EZ    11.0
4                              heightMin   285.0
..                                   ...     ...
70                               Persons     0.0
71                                 ICapP   150.0
72                                ICapIP     1.5
73                             PCritflux   100.0
74                            IPCritflux    10.0

[75 rows x 2 columns]

### For fixing the HSO bug with glacier fraction:

In [4]:
import pandas as pd
import numpy as np

# catchment = "Gaupne"
# catchment = "Austdalsvatnet"
catchment = "Tunsbergdalsvatnet"
# catchment = "Myklemyr"
# catchment = "BåtedølaS"
# catchment = "Geisdalsvatnet"

def parameter_editor_2(file_path, catchment):
    df = pd.read_csv(file_path, sep=";", header=None)

    print(f"{catchment}:")
    print(f"Glacier fraction = {df.iloc[41,1]*100} %")
    print(f"Catchment area = {df.iloc[28, 1]} m^2")
    print(" ")
    print("Previous values")
    print(f"maxGl = {df.iloc[45,1]} ")
    print(f"midGl = {df.iloc[50,1]} ")
    print(f"stdGl = {df.iloc[52,1]} ")
    
    glac_frac = df.iloc[41,1]
    catchment_area = df.iloc[28, 1]
    glac_area=glac_frac*catchment_area
    
    
    maxGl_new = round((4*glac_area/np.pi)**(1/2), 2)
    midGl_new = round(maxGl_new/2, 2)
    stdGl_new = round(midGl_new/2, 2)
    
    df.iloc[45, 1] = maxGl_new
    df.iloc[50, 1] = midGl_new
    df.iloc[52, 1] = stdGl_new
    print(" ")     
    print("New values")
    print(f"maxGl_new = {df.iloc[45,1]} ")
    print(f"midGl_new = {df.iloc[50,1]} ")
    print(f"stdGl_new = {df.iloc[52,1]} ")
    


    df.to_csv(file_path, sep=";", header=False, index=False)

    print(f"File saved as: {file_path}")
    return df

file_path = f"{catchment}_3H_param_edited.csv"
parameter_editor_2(file_path, catchment)

Tunsbergdalsvatnet:
Glacier fraction = 42.57 %
Catchment area = 137200000.0 m^2

Previous values
maxGl = 101009214.95
midGl = 50504607.48
stdGl = 25252303.74

New values
maxGl_new = 8623.51
midGl_new = 4311.76
stdGl_new = 2155.88
File saved as: Tunsbergdalsvatnet_3H_param_edited.csv

                                       0       1
0                               OBJECTID  3543.0
1                                     ID     1.0
2   f363342e-96b5-4ece-9d41-b4ecf40a5bb3    10.0
3                                 076.BA    11.0
4                              heightMin   452.0
..                                   ...     ...
70                               Persons     0.0
71                                 ICapP   150.0
72                                ICapIP     1.5
73                             PCritflux   100.0
74                            IPCritflux    10.0

[75 rows x 2 columns]

## For editing the Gsc parameter manually, testing purposes

In [4]:
import pandas as pd
import numpy as np

# catchment = "Gaupne"
# catchment = "Austdalsvatnet"
# catchment = "Tunsbergdalsvatnet"
catchment = "Myklemyr"

def parameter_editor_3(file_path, catchment):
    df = pd.read_csv(file_path, sep=";", header=None)

    print(f"{catchment}:")

    print(" ")
    print("Previous value")
    print(f"GscInt = {df.iloc[32,1]} ")
    
    GscInt_new = 0.105864
    u_new = 1.62239
    Pkorr_new = 0.549656
    
    df.iloc[32, 1] = GscInt_new
    df.iloc[19, 1] = u_new
    df.iloc[17, 1] = Pkorr_new
    
    print("New value")
    print(f"GscInt = {df.iloc[32,1]} ")
    
    df.to_csv("Myklemyr_manualtesting", sep=";", header=False, index=False)

    print(f"File saved as: Myklemyr_manualtesting")
    return df

file_path = f"{catchment}_1H_param_edited.csv"
parameter_editor_3(file_path, catchment)

Myklemyr:

Previous value
GscInt = 0.0029829848634152
New value
GscInt = 0.105864
File saved as: Myklemyr_1H_param_edited.csv_manualtesting

                                       0       1
0                               OBJECTID  3542.0
1                                     ID     1.0
2   f685f13d-1eff-409a-8e63-fb5cc2b19e71    10.0
3                                076.D10    11.0
4                              heightMin    79.0
..                                   ...     ...
70                               Persons     0.0
71                                 ICapP   150.0
72                                ICapIP     1.5
73                             PCritflux   100.0
74                            IPCritflux    10.0

[75 rows x 2 columns]